# Save into your repo as .github/workflows/on-tag.yaml
name: On Tag
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Build and Push
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config
          ./acorn login -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io
          ./acorn build -t ghcr.io/${{ github.repository }}:main .
          ./acorn push ghcr.io/${{ github.repository }}:main
