name: On Tag
on:
  push:
    tags:
    - "v*"
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Set Tag
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Build and Push
        run: |
          mkdir -p $HOME/.kube
          echo "$KUBECONFIG" > $HOME/.kube/config
          ./acorn login -u "${{ github.actor }}" -p "${{ secrets.GITHUB_TOKEN }}" ghcr.io
          ./acorn build -t ghcr.io/${{ github.repository }}:$TAG .
          ./acorn push ghcr.io/${{ github.repository }}:$TAG
